##################################################################
# Debug Parameters
##################################################################
DEBUG_MODE : false
save_plots_loc : images/
jupyter : false

##################################################################
# Dataset Parameters
##################################################################
ds_loc : ../face_detect/datasets/archive/ # Dataset Location
data_count : 50 # a number or full
num_classes : 4 # if one class, then use 0
#=================================================================
img_size : 416 # n x n , should be a multiple of 32

##################################################################
# Training Parameters
##################################################################
num_anchors : 2
